version: '3.8'

services:
  wordgame-client:
    volumes:
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock # Share the SSH agent socket
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
